### ISSUE TITLE
Authentication feature for multiple account same device login

### ISSUE THREAD

**Issue by Abdel004** [portto/blocto-sdk#26]
I am currently allowing users to log in/signup by using the fcl API to interact with blocto.

Assume we have users A and B who both use the same device.

User A logs into his account to do some transactions then logs out and leaves the device. User B then tries to log in but when he presses the login button, they see the following.

![7ba888e7cdd2e274c5894e352548c89d](https://user-images.githubusercontent.com/90336476/174215441-2650f455-bec5-4168-af2c-913639b584df.jpg)

So now User B can either press confirm and log into user's A account or click the "use Another Account" button to log into his account.

What is mentioned above is very inconvenient especially if a user has multiple accounts and wants to perform transactions on one account but presses "confirm" by mistake and accidentally performs the transactions on a different account.

What I am asking is if there is a way to the following whenever a user presses the login button

![87e114e3eb5ae48e1c5afc94e3a03143](https://user-images.githubusercontent.com/90336476/174215462-a287c1e5-af29-4463-8d36-b3b981c8963f.jpg)

Also, if there is already a workaround solution, could someone please guide me on how to overcome this issue?

**Comment by akira02** [comment]
There is a workaround solution:
After disconnect, click connect again, select "Use another account", and close popup without typing new email.
When clicking "Use another account", the session that store your email will be removed. 

Since fcl.js also only has "disconnect" method, I have no idea how to add a method that support "deeply logout".
You can open a new issue discuss with fcl.js here: https://github.com/onflow/fcl-js/
